version: '3'
services:

  dvd:
    image: jlesage/makemkv
    restart: always
    env_file: makemkv.env
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - config:/config:rw
      - storage:/storage:ro
      - output:/output:rw
    devices:
      - "/dev/sr1:/dev/sr1"
      - "/dev/sg2:/dev/sg2"

  blu:
    image: jlesage/makemkv
    restart: always
    env_file: makemkv.env
    ports:
      - "5801:5800"
      - "5901:5900"
    volumes:
      - config:/config:rw
      - storage:/storage:ro
      - output:/output:rw
    devices:
      - "/dev/sr0:/dev/sr0"
      - "/dev/sg1:/dev/sg1"

volumes:
    config:
        driver: local
    storage:
        driver: local
    output:
        driver: local
