version: '3'
services:
  blu:
    image: jlesage/makemkv
    restart: always
    env_file: makemkv.env
    ports:
      - "5801:5800"
    volumes:
      - config:/config:rw
      - storage:/storage:ro
      - output:/output:rw
    devices:
      - "/dev/sg1:/dev/sg1"
      - "/dev/sr1:/dev/sr1"

  dvd:
    image: jlesage/makemkv
    restart: always
    env_file: makemkv.env
    ports:
      - "5800:5800"
    volumes:
      - config:/config:rw
      - storage:/storage:ro
      - output:/output:rw
    devices:
      - "/dev/sg1:/dev/sg0"
      - "/dev/sr1:/dev/sr0"


volumes:
    config:
        driver: local
    storage:
        driver: local
    output:
        driver: local
